# Generated by Django 5.1 on 2024-11-17 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_remove_service_category_department_doctors_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorearnings',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='departments.doctorprofile'),
        ),
    ]
