# Generated by Django 5.1.3 on 2024-11-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_doctorearnings_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='per_patient_rate',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='percentage_per_consultation',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='total_consultation_fee',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='total_patients_admitted',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
