# Generated by Django 5.1.3 on 2024-11-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_payment_appointment_remove_payment_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryconfiguration',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='SalaryConfiguration',
        ),
    ]
