# Generated by Django 5.1 on 2024-11-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_ipdconsumable_ipdmedication'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('IPD', 'In-Patient'), ('OPD', 'Out-Patient')], default='OPD', max_length=3),
        ),
    ]
