# Generated by Django 5.1.3 on 2024-11-24 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_consumable_price_per_unit_and_more'),
        ('patient', '0003_patient_patient_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipdmedication',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='ipdmedication',
            name='patient',
        ),
        migrations.CreateModel(
            name='TreatmentConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.consumable')),
                ('treatment_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_consumables', to='patient.treatmenthistory')),
            ],
        ),
        migrations.AddField(
            model_name='treatmenthistory',
            name='consumables',
            field=models.ManyToManyField(through='patient.TreatmentConsumable', to='inventory.consumable'),
        ),
        migrations.CreateModel(
            name='TreatmentMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medication')),
                ('treatment_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_medications', to='patient.treatmenthistory')),
            ],
        ),
        migrations.AddField(
            model_name='treatmenthistory',
            name='medications',
            field=models.ManyToManyField(through='patient.TreatmentMedication', to='inventory.medication'),
        ),
        migrations.DeleteModel(
            name='IPDConsumable',
        ),
        migrations.DeleteModel(
            name='IPDMedication',
        ),
    ]
