# Generated by Django 5.1.3 on 2024-11-25 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_remove_invoice_status_payment'),
        ('patient', '0006_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='treatment_notes',
            field=models.TextField(help_text='Notes on treatment and procedures performed'),
        ),
    ]
