# Generated by Django 5.1.3 on 2024-11-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_diagnosis_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('IPD', 'Inpatient'), ('OPD', 'Outpatient')], default='OPD', max_length=3),
        ),
    ]
