# Generated by Django 5.1 on 2024-11-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('opd', 'Outpatient'), ('ipd', 'Inpatient')], default='opd', max_length=10),
        ),
    ]
