# Generated by Django 5.1.3 on 2024-11-24 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointment_appointment_type'),
        ('inventory', '0002_remove_consumable_price_per_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.consumable')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('treatment_notes', models.TextField(help_text='Notes on treatment and procedures performed')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_history', to='appointments.appointment')),
                ('consumables', models.ManyToManyField(through='appointments.TreatmentConsumable', to='inventory.consumable')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='treatmentconsumable',
            name='treatment_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_consumables', to='appointments.treatmenthistory'),
        ),
        migrations.CreateModel(
            name='TreatmentMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medication')),
                ('treatment_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_medications', to='appointments.treatmenthistory')),
            ],
        ),
        migrations.AddField(
            model_name='treatmenthistory',
            name='medications',
            field=models.ManyToManyField(through='appointments.TreatmentMedication', to='inventory.medication'),
        ),
    ]
