# Generated by Django 5.1.3 on 2024-11-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_remove_invoice_status_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('IPD', 'Outpatient'), ('OPD', 'Inpatient')], default='opd', max_length=10),
        ),
    ]
