# Generated by Django 5.1.3 on 2024-11-30 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_appointment_appointment_type'),
        ('departments', '0010_alter_bed_bed_number_alter_room_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged')], default='admitted', max_length=20)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='appointments.appointment')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='departments.bed')),
            ],
        ),
    ]
