# Generated by Django 5.1.3 on 2024-12-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_admission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
