# Generated by Django 5.1.3 on 2024-12-01 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_delete_admission'),
        ('departments', '0012_alter_bed_unique_together_alter_room_unique_together_and_more'),
        ('patient', '0009_remove_patient_patient_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('OPD', 'Outpatient'), ('IPD', 'Inpatient')], default='OPD', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'roles__name': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_services', to='departments.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='IPDAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged')], default='admitted', max_length=20)),
                ('visit_type', models.CharField(choices=[('OPD', 'Outpatient'), ('IPD', 'Inpatient')], default='IPD', max_length=10)),
                ('bed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.bed')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='departments.department')),
                ('doctor', models.ForeignKey(limit_choices_to={'roles__name': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.floor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='patient.patient')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.room')),
                ('services', models.ManyToManyField(blank=True, related_name='%(class)s_services', to='departments.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
