# Generated by Django 5.1.3 on 2024-12-01 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_alter_appointment_status'),
        ('departments', '0016_bed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdadmission',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='departments.bed'),
        ),
    ]
