# Generated by Django 5.1.3 on 2024-12-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_alter_ipdadmission_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdadmission',
            name='bed_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
