# Generated by Django 5.1.3 on 2024-12-03 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_alter_invoice_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='ipdadmission',
            name='bed_price',
        ),
        migrations.AddField(
            model_name='treatmenthistory',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_history', to='appointments.ipdadmission'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='appointments.appointment'),
        ),
    ]
