# Generated by Django 5.1.3 on 2024-12-03 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_remove_invoice_admission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmenthistory',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.ipdadmission'),
        ),
        migrations.AlterField(
            model_name='treatmenthistory',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
    ]
