# Generated by Django 5.1.3 on 2024-12-03 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_alter_treatmenthistory_admission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmenthistory',
            name='admission',
        ),
        migrations.AlterField(
            model_name='treatmenthistory',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_history', to='appointments.appointment'),
        ),
    ]
