# Generated by Django 5.1 on 2024-11-10 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='doctors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'doctor'}, related_name='departments_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='nurses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'nurse'}, related_name='departments_as_nurse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='assigned_services',
            field=models.ManyToManyField(blank=True, related_name='nurses', to='departments.service'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='assigned_services',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='departments.service'),
        ),
        migrations.AddField(
            model_name='department',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='departments', to='departments.service'),
        ),
    ]
