# Generated by Django 5.1 on 2024-11-17 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_staffavailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='default_availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('vacation', 'Vacation')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='doctors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'roles__name': 'Doctor'}, related_name='departments_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='nurses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'roles__name': 'Nurse'}, related_name='departments_as_nurse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffavailability', to=settings.AUTH_USER_MODEL),
        ),
    ]
