# Generated by Django 5.1 on 2024-11-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_doctorprofile_default_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffavailability',
            name='department',
        ),
    ]
