# Generated by Django 5.1 on 2024-11-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_remove_staffavailability_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='default_availability',
        ),
    ]
