# Generated by Django 5.1.3 on 2024-12-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0013_room_room_number_alter_bed_bed_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
    ]
