# Generated by Django 5.1.3 on 2024-12-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0014_alter_room_unique_together_remove_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('floor', 'room_number')},
        ),
    ]
