# Generated by Django 5.1.3 on 2024-12-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0015_room_room_number_alter_room_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
